name: Checks

on:
  push:

env:
  PIP_PROGRESS_BAR: "off"

jobs:

  install:
    name: Install (py${{ matrix.python-version }}/${{ matrix.os }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']
        os:
          - linux
          - win64
        include:
          - os: linux
            runner: ubuntu-20.04
          - os: win64
            runner: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python package
        run:
          pip install .
      - name: Show installed packages
          pip list
          pip show dispatches-prescient-sweeps
